version: 2.1

orbs:
  cloudformation: orbss/aws-cloudformation@0.1.4

workflows:
  version: 2
  cloudformation/create-stack:
    stack-name: stopcovid19-static-page
    template-file-path:
    branch: master 
    extra-arguments: --parameters BucketName=stopcovid19-dev

  cloudformation/create-stack:
    stack-name: stopcovid19-static-page-dev
    template-file-path: staticpage-template.yaml
    branch: dev 
    extra-arguments: --parameters BucketName=stopcovid19-dev

    cloudformation/deploy-stack:
      stack-name: stopcovid19-static-page-dev
      template-file-path: staticpage-template.yaml
      branch: dev 
      capabilities: CAPABILITY_IAM 
    
    cloudformation/deploy-stack:
      stack-name: stopcovid19-static-page
      template-file-path: staticpage-template.yaml
      branch: master
      capabilities: CAPABILITY_IAM 