version: 2.1

orbs:
  cloudformation: orbss/aws-cloudformation@0.1.6

workflows:
  version: 2
  build-deploy-stack:
    jobs:      
      - cloudformation/create-stack:
          filters: 
            branches: 
              only: 
                - dev 
                - master

          stack-name: stopcovid19-static-page-${CIRCLE_BRANCH}
          template-file-path: staticpage-template.yaml
          extra-arguments: --parameters ParameterKey=BucketName,ParameterValue=stopcovid19-${CIRCLE_BRANCH}
          capabilities: CAPABILITY_IAM


      - cloudformation/deploy:
          requires:
            - cloudformation/create-stack
          stack-name: stopcovid19-static-page-${CIRCLE_BRANCH}
          template-file-path: staticpage-template.yaml
          capabilities: CAPABILITY_IAM
 